services:
  client:
    container_name: anonymous_blog_client
    build: ./client
    image: anonymous_blog_client
    ports: 
      - 8080:8080
    working_dir: /code
    volumes:
      - type: bind
        source: ./client
        target: /code
    command: [ "http-server" ]
  api:
    container_name: anonymous_blog_dev_api
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=dimi_imman
      - PGHOST=db
      - PGPASSWORD=anonymouspass
      - PGDATABASE=anonymous
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"

  db:
    container_name: anonymous_blog_dev_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=anonymous
      - POSTGRES_USER=dimi_imman
      - POSTGRES_PASSWORD=anonymouspass
volumes:
  dbdata:
networks: 
  default:
    name: anonymous_blog_api
    
